CREATE TABLE dbo.characters
(
    [
    CHARACTER_ID]
    INT
    NOT
    NULL
    IDENTITY
(
    1,
    1
), [PLAYER_ID] INT NOT NULL, [CLASS] VARCHAR(32) NOT NULL, [SPEC] VARCHAR(32) NOT NULL, [RAID_ROLE] VARCHAR(32) NOT NULL, PRIMARY KEY ([CHARACTER_ID])
    )

CREATE TABLE dbo.player
(
    [
    PLAYER_ID]
    INT
    NOT
    NULL
    IDENTITY
(
    1,
    1
), [PLAYER_NAME] VARCHAR(32) NOT NULL, [DISCORD_ID] BIGINT NOT NULL, [VACATION_START] DATE, [VACATION_END] DATE, [FLASK_SPEND] INT, [ID_JOINED] INT NOT NULL, [IS_TRIAL] BINARY NOT NULL, PRIMARY KEY ([PLAYER_ID])
    )

CREATE TABLE dbo.reminder
(
    [
    ID]
    INT
    NOT
    NULL
    IDENTITY
(
    1,
    1
), [PLAYER_ID] INT NOT NULL, [LAST_FLASK_REMINDER] DATE, [LAST_RAID_REMINDER] DATE, PRIMARY KEY ([ID])
    )

ALTER TABLE dbo.characters
    ADD CONSTRAINT [PLAYER_ID_characters]
    FOREIGN KEY ([PLAYER_ID]) REFERENCES dbo.player ([PLAYER_ID]);

ALTER TABLE dbo.reminder
    ADD CONSTRAINT player_reminder
        FOREIGN KEY ([PLAYER_ID]) REFERENCES dbo.player ([PLAYER_ID]);