CREATE TABLE subot.characters(
    `CHARACTER_ID` INT NOT NULL AUTO_INCREMENT,
    `PLAYER_ID` INT NOT NULL,
    `CLASS` VARCHAR(32) NOT NULL,
    `SPEC` VARCHAR(32) NOT NULL,
    `RAID_ROLE` VARCHAR(32) NOT NULL,
    PRIMARY KEY(`CHARACTER_ID`)
);

CREATE TABLE subot.player(
    `PLAYER_ID` INT NOT NULL AUTO_INCREMENT,
    `PLAYER_NAME` VARCHAR(32) NOT NULL,
    `DISCORD_ID` BIGINT NOT NULL,
    `VACATION_START` DATE,
    `VACATION_END` DATE,
    `FLASK_PAID_UNTIL` DATE,
    `IS_MUTED` INT DEFAULT 0,
    `IS_TRIAL` BINARY NOT NULL,
    PRIMARY KEY(`PLAYER_ID`)
);

-- Migration from old schema (if upgrading):
-- ALTER TABLE player ADD COLUMN FLASK_PAID_UNTIL DATE;
-- UPDATE player SET FLASK_PAID_UNTIL = DATE_ADD(CURDATE(), INTERVAL ((FLASK_SPEND / 18) - WEEK(CURDATE()) + ID_JOINED) WEEK);
-- ALTER TABLE player DROP COLUMN FLASK_SPEND;
-- ALTER TABLE player DROP COLUMN ID_JOINED;

CREATE TABLE subot.reminder(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `PLAYER_ID` INT NOT NULL,
    `LAST_FLASK_REMINDER` DATE,
    `LAST_RAID_REMINDER` DATE,
    PRIMARY KEY(`ID`)
);

CREATE TABLE subot.messages(
    `MSG_ID` INT NOT NULL AUTO_INCREMENT,
    `DATE` DATE NOT NULL,
    `TIME` VARCHAR(32) NOT NULL,
    `SENDER` VARCHAR(32) NOT NULL,
    `MSG` VARCHAR(32) NOT NULL,
    `RECEIVER` VARCHAR(32) NOT NULL,
    PRIMARY KEY(`MSG_ID`)
);

ALTER TABLE
    subot.characters ADD CONSTRAINT `PLAYER_ID_characters` FOREIGN KEY(`PLAYER_ID`) REFERENCES player(`PLAYER_ID`);
ALTER TABLE
    subot.reminder ADD CONSTRAINT player_reminder FOREIGN KEY(`PLAYER_ID`) REFERENCES player(`PLAYER_ID`);